listen: 0.0.0.0:8000
name: reactions
server_read_timeout: 10s
server_write_timeout: 10s

log:
  level: debug
  output:
    - stdout  # 'stdout' and 'stderr' are special values indicating output should go system stdout or stderr
    - app.log # show file with line which did logging
  caller: true
  stacktrace: true # show stack trace in case of error
