listen: 0.0.0.0:8000
name: reactions
shutdown_timeout: 10s
server_read_timeout: 10s
server_write_timeout: 10s

log:
  level: debug
  output:
    - stdout  # 'stdout' and 'stderr' are special values indicating output should go system stdout or stderr
    - app.log # show file with line which did logging
  caller: true
  stacktrace: true # show stack trace in case of error

socket: # configs for websocket connections
  handshake_timeout: 8s # timeout in which the handshake should be made
  read_buffer_size: 4096 # size of message (in bytes) on read
  write_buffer_size: 4096 # size of message (in bytes) on write
